services:
  go:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    # ports from container exposed to the docker machine and the guest machine
    ports:
      # 80 on the host, 8080 on the guest. Websever listens on 8080
      - "80:9000" # http
      - "443:443" # https
    # file with environment declarations for the container
    env_file:
      - docker/.env
    # Link to containers in another service
    links:
      - mysql
    # sync workspace folder with /go
    volumes:
     - ../../../../.:/go
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: goback